builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    main: ./
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -extldflags '-static'
      - -s -w
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'

changelog:
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
