name: Run Makefile CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  make-action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8

      - name: Run tests
        run: make test
